### ISSUE TITLE
Überarbeitung der Tracking Seite

### ISSUE THREAD

**Issue by mide-ba** [nise/theresienstadt-explained#57]
- [x] Tracking Seite führt Lehrenden Schritt für Schritt durch den Prozess -> selbsterklärend

- [x] Knöpfe oder divs werden nur eingeblendet wenn gebraucht

- [x] Ansicht des Status der Lernenden ist kompakt und lässt einen schnellen Überblick zu
